//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int Patient_ID { get; set; }
        public string Insurance_Company { get; set; }
        public Nullable<int> Insurance_No { get; set; }
        public Nullable<int> Co_Pay_Amount { get; set; }
        public Nullable<int> Total_Amount { get; set; }
    }
}
