//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrMed
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracking
    {
        public int Patient_ID { get; set; }
        public string doctor_visited { get; set; }
        public string payment_paid { get; set; }
        public string appointment_booked { get; set; }
    }
}
